"$schema" = 'https://starship.rs/config-schema.json'

format = "$all $fill $jobs$time$line_break$character"
command_timeout = 1000

[fill]
symbol = " "

[directory]
truncation_length = 8

[time]
disabled = false
time_format = "%R"
format = '[♥](bold red) [$time](cyan)'

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[ruby]
disabled = true

[nodejs]
disabled = true
