[misc]
no_retry = true
cleanup = true
disable = ["git_repos", "node"]

[python]
enable_pipupgrade = true

[brew]
autoremove = true
fetch_head = false
greedy_auto_updates = true
greedy_cask = false

[commands]
"Catppuccin Colors" = "export CATPPUCCIN_COLORS=$(vivid generate catppuccin-mocha); export LS_COLORS=$CATPPUCCIN_COLORS; echo $CATPPUCCIN_COLORS > ~/.config/zsh/static/catppuccin-colors.txt && echo 'Catppuccin colors updated!'"
"Ruby Update" = "mise upgrade ruby && gem update --system && gem update"
"Python Packages" = "VENV_DIR=\"$HOME/.local/share/venv\"; if [ ! -d \"$VENV_DIR\" ] || [ ! -f \"$VENV_DIR/bin/python\" ]; then echo \"Creating/Recreating Python virtual environment\"; rm -rf \"$VENV_DIR\"; python3 -m venv \"$VENV_DIR\"; fi; source \"$VENV_DIR/bin/activate\" && pip install --upgrade pip && pip list --outdated | awk '{if(NR>2)print $1}' | xargs -n1 pip install -U || true"
