"$schema" = 'https://starship.rs/config-schema.json'

format = "${custom.special-emoji}$all $fill $jobs ${custom.clock-emoji} $time $line_break$character"
command_timeout = 1000

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[fill]
symbol = " "

[directory]
truncation_length = 8

[time]
disabled = false
time_format = "%R"
format = '[$time](bold cyan)'

[git_status]
ahead = " ${count}"
diverged = "󰹹 ${ahead_count} ${behind_count}"
behind = " ${count}"

[git_branch]
symbol = "󰘬 "

[ruby]
disabled = true

[dotnet]
disabled = true

[nodejs]
disabled = true

[custom.clock-emoji]
when = true
command = 'echo -n "$STARSHIP_CLOCK"'
format = "[$output](bold white) "
ignore_timeout = true

[custom.special-emoji]
when = true
command = 'echo -n "$STARSHIP_EMOJI"'
format = "[$output](bold cyan)  "
ignore_timeout = true
